#!/bin/sh

export HOME=/
export PATH=/sbin:/bin:/usr/sbin:/usr/bin:/usr/pkg/bin:/usr/pkg/sbin
umask 022

mount -a

[ -f /etc/rc.conf ] && . /etc/rc.conf

/etc/rc.d/bootconf.sh start

# usually done by /sbin/init
cd /dev && sh MAKEDEV -M all
cd -

# basic services to start at boot
STARTSVC="
ttys
sysctl
entropy
network
local
"

for svc in $STARTSVC
do
	/etc/rc.d/${svc} start
done

chmod 666 /dev/null

cp /etc/banner.ans /etc/motd
printf "\e[0m  :: powered by 🚩 \e[38;5;208mNetBSD\e[0m $(uname -r)\n\n" \
	>>/etc/motd
