#!/bin/sh

. /etc/include/basicrc

mount -t tmpfs -o -s1M tmpfs /home
mount -t tmpfs -o -s10M tmpfs /tmp
mount -t tmpfs -o -s10M tmpfs /var/log
mount -t tmpfs -o -s1M tmpfs /var/run
mkdir /tmp/etc
(cd /etc && tar cfp - .)|(cd /tmp/etc && tar xfp -)
mount -t tmpfs -o -s10M tmpfs /etc
(cd /tmp/etc && tar cfp - .)|(cd /etc && tar xfp -)
rm -rf /tmp/*

useradd -m ssh
mkdir -p /home/ssh/.ssh
cp -f /etc/ssh/authorized_keys /home/ssh/.ssh
chown -R ssh /home/ssh

/etc/rc.d/sshd onestart

. /etc/include/shutdown
