#!/bin/sh

. /etc/include/basicrc

export PATH=/sbin:/bin:/usr/sbin:/usr/bin:/usr/pkg/bin:/usr/pkg/sbin
export TERM=tmux-256color
eval $(resize) # get current window size

route flush -inet6 >/dev/null 2>&1

lightgreen="\033[92m"
bold="\033[1m"
normal="\033[0m"

printbold()
{
	printf "${bold}$1${normal}\n"
}

export NBUSER=nbuser
export NBHOME=/home/${NBUSER}
export TMUX_SOCKET=${NBHOME}/tmp/tmux
export CHOUPI=y

if [ ! -d ${NBHOME} ]; then
	. /etc/include/pkgin

	PACKAGES="bash git-base neovim curl doas ripgrep fd-find bat fzf gmake"

	if ! id NBUSER >/dev/null 2>&1; then
	
		printbold "⭐ creating user"
		useradd -m $NBUSER

		printbold "⭐ installing user packages"
		echo "➡️  $PACKAGES"
		pkgin -y in $PACKAGES

		export HOSTNAME_FG="blanc"
		export HOSTNAME_BG="violet"

		printbold "⭐ setup powerline.bash"
		curl -o- -s \
			https://gitlab.com/-/snippets/4796585/raw/main/mkchoupi.sh | \
			bash > ${NBHOME}/.bashoupi

		printbold "⭐ cloning tmux-power"
		mkdir -p ${NBHOME}/.tmux
		curl -s -Lo ${NBHOME}/.tmux/tmux-power.tmux \
			https://raw.githubusercontent.com/wfxr/tmux-power/master/tmux-power.tmux
		sed -i.bak 's/status-right "$RS"/status-right ":: powered by 🚩 + smolBSD "/' \
				${NBHOME}/.tmux/tmux-power.tmux
		chmod +x ${NBHOME}/.tmux/tmux-power.tmux

		# nvim is the only editor I found that does not mess
		# with tab display in qemu stdio mode
		printbold "⭐ kawaï nvim"
		mkdir -p ${NBHOME}/.local/share/nvim/site/autoload
		curl -s -Lo ${NBHOME}/.local/share/nvim/site/autoload/plug.vim \
			https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
		mkdir -p ${NBHOME}/.config/nvim
		curl -s -Lo ${NBHOME}/.config/nvim/init.lua \
			https://gitlab.com/-/snippets/4797133/raw/main/init.lua

		printbold "⭐ creating a sane bach_profile"
		chsh -s /usr/pkg/bin/bash ${NBUSER}
		cat >/home/${NBUSER}/.bash_profile<<EOF
export HOME=${NBHOME}
export EDITOR=nvim
export VISUAL=\${EDITOR}
export PAGER=less
export NBUSER=${NBUSER}
export PATH=/sbin:/bin:/usr/sbin:/usr/bin:/usr/pkg/bin:/usr/pkg/sbin

lightgreen="${lightgreen}"
bold="${bold}"
normal="${normal}"

LANG=en_US.UTF-8; export LANG

alias cat="bat -pp"
alias less="bat -p"
alias vim=nvim
alias vi=nvim

stty speed 115200 >/dev/null

. \${HOME}/.bashoupi

# download modules, ignore complains about modules not being installed
[ ! -d \${HOME}/.local/share/nvim/plugged ] && \
		nvim --headless +PlugInstall +qall 2>/dev/null

if [ -d /tmp/tmux* -a ! -f /tmp/greetings ]; then
	echo -e "
Welcome to the (n)bakery! 🧁

💪 \${lightgreen}doas <command>\${normal} to run command as \${bold}root\${normal}
📦 \${lightgreen}pkgin\${normal} to manage packages
🚪 \${lightgreen}exit\${normal} to cleanly shutdown, \${lightgreen}^a-x\${normal} to exit \${lightgreen}qemu\${normal}
🪟 you are inside a \${lightgreen}tmux\${normal} with prefix \${lightgreen}^q\${normal}
"
	touch /tmp/greetings
fi

EOF
echo "rm -f /tmp/greetings" > ${NBHOME}/.bash_logout

		printbold "⭐ customizing tmux"
		cat >${NBHOME}/.tmux.conf<<EOF
# spawn a login shell in order to read ~/.bash_profile
unbind C-b
set -g prefix ^Q
bind q send-prefix
set-option -g default-command "bash -l"
set -g default-terminal "tmux-256color"
set -g @tmux_power_theme 'moon'
run '~/.tmux/tmux-power.tmux'
EOF
		chown -R ${NBUSER} ${NBHOME} ${NBHOME}/.*

		printbold "⭐ adding $NBUSER to group wheel"
		usermod -G wheel $NBUSER
		printbold "⭐ permit $NBUSER to ${lightgreen}doas${normal}"
		echo "permit nopass keepenv setenv { PATH } :wheel" \
			>/usr/pkg/etc/doas.conf
	fi
fi

printbold "⭐ checking for exported filesystem"
if dmesg |grep -q vio9; then
	cp -f /etc/MAKEDEV /dev
	(cd /dev && sh MAKEDEV vio9p0)
	mount_9p -cu /dev/vio9p0 /mnt
	echo "➡️ host filesystem mounted on /mnt"
fi

hostname nbakery

su - ${NBUSER} -c "tmux -u new"

. /etc/include/shutdown
