#!/bin/sh

. /etc/include/basicrc
. /etc/include/pkgin
. /etc/include/mount9p

command -v perl >/dev/null || pkgin -y in perl git-base

# newer NetBSD versions use tmpfs for /dev, sailor copies MAKEDEV from /dev
cp /etc/MAKEDEV /dev/

resize
export TERM=vt220
ksh

. /etc/include/shutdown
