#!/bin/sh

. /etc/include/basicrc

wwwroot=/var/www

[ ! -f /var/www/index.html ] && \
	echo "<html><body>up!</body></html>" >${wwwroot}/index.html

/usr/libexec/bozohttpd -f ${wwwroot}

. /etc/include/shutdown
