#!/bin/sh

. /etc/include/basicrc

# install necesary packages
if [ ! -d /var/db/pkgin ]; then
	echo -e "\nInstalling needed packages\n"

	ver=$(uname -r)
	case $ver in
	*99*) # current
		ver=${ver%.99*}.0
		;;
	*_*) # tag
		ver=${ver%_*}
		;;
	esac

	# repository path differs for amd64 or aarch64/evbarm
	machine=$(uname -m)
	proc=$(uname -p)
	[ "$machine" = "amd64" ] && arch=$machine || arch=$proc
	url="http://cdn.netbsd.org/pub/pkgsrc/packages/NetBSD/${arch}/${ver}/All"
	
	echo "fetching $url"
	
	for pkg in pkg_install pkgin mozilla-rootcerts pkg_tarup rsync curl
	do
		pkg_info $pkg >/dev/null 2>&1 || pkg_add -v ${url}/${pkg}*
	done

	mkdir -p /usr/pkg/etc/pkgin
	echo $url >/usr/pkg/etc/pkgin/repositories.conf
	pkgin up
fi

# newer NetBSD versions use tmpfs for /dev, sailor copies MAKEDEV from /dev
cp /etc/MAKEDEV /dev/

cd sailor
ship=$(basename *.conf .conf)
mkdir $ship
[ "$(uname -p)" = "aarch64" ] && dsk=ld4 || dsk=ld1
newfs /dev/${dsk}a
mount /dev/${dsk}a $ship
# use sailor to create a minimal root fs
/bin/sh ./sailor.sh build ${ship}.conf
# copy basicrc and shutdown
mkdir -p ${ship}/etc/include
cp /etc/include/* ${ship}/etc/include
cat >${ship}/etc/fstab<<EOF
ROOT.a / ffs rw 1 1
EOF

# customize image

. /etc/svc
[ -f /etc/rc.${SVCIMG} ] && . /etc/rc.${SVCIMG}

echo -e "\n$ship image created! You can now ^D to cleanly shutdown.\n"

ksh

. /etc/include/shutdown
