#!/bin/sh

. /etc/include/basicrc
. /etc/include/pkgin

# newer NetBSD versions use tmpfs for /dev, sailor copies MAKEDEV from /dev
cp /etc/MAKEDEV /dev/

cd sailor
ship=$(basename *.conf .conf)
mkdir $ship
[ "$(uname -p)" = "aarch64" ] && dsk=ld4 || dsk=ld1
newfs /dev/${dsk}a
mount /dev/${dsk}a $ship
# use sailor to create a minimal root fs
/bin/sh ./sailor.sh build ${ship}.conf
# copy basicrc and shutdown
mkdir -p ${ship}/etc/include
cp /etc/include/* ${ship}/etc/include
cat >${ship}/etc/fstab<<EOF
ROOT.a / ffs rw 1 1
EOF

# customize image

[ -f /etc/svc ] && . /etc/svc
[ -f /etc/rc.${SVCIMG} ] && . /etc/rc.${SVCIMG}

echo -e "\n$ship image created! You can now ^D to cleanly shutdown.\n"

ksh

. /etc/include/shutdown
