#!/bin/sh

. /etc/include/basicrc

# install necesary packages
if [ ! -d /var/db/pkgin ]; then
	echo -e "\nInstalling needed packages\n"

	ver=$(uname -r)
	case $ver in
	*99*) # current
		ver=${ver%.99*}.0
		;;
	*_*) # tag
		ver=${ver%_*}
		;;
	esac

	arch=$(uname -m)
	url="http://cdn.netbsd.org/pub/pkgsrc/packages/NetBSD/${arch}/${ver}/All"
	
	echo "fetching $url"
	
	for pkg in pkg_install pkgin mozilla-rootcerts pkg_tarup rsync curl
	do
		pkg_info $pkg >/dev/null 2>&1 || pkg_add -v ${url}/${pkg}*
	done

	mkdir -p /usr/pkg/etc/pkgin
	echo $url >/usr/pkg/etc/pkgin/repositories.conf
	pkgin up
fi

# newer NetBSD versions use tmpfs for /dev, sailor copies MAKEDEV from /dev
cp /etc/MAKEDEV /dev/

cd sailor
ship=$(basename *.conf .conf)
mkdir $ship
newfs /dev/ld1a
mount /dev/ld1a $ship
/bin/sh ./sailor.sh build ${ship}.conf


echo -e "\n$ship image created! You can now ^D to cleanly shutdown.\n"

ksh

. /etc/include/shutdown
